import type { Report, Finding } from "./types.js";

const c = {
  reset: "\x1b[0m", bold: "\x1b[1m", dim: "\x1b[2m",
  green: "\x1b[32m", yellow: "\x1b[33m", red: "\x1b[31m", cyan: "\x1b[36m",
};

function colorFor(score: number): string {
  if (score >= 90) return c.green;
  if (score >= 50) return c.yellow;
  return c.red;
}

const sevIcon: Record<Finding["severity"], string> = {
  error: "✖", warning: "▲", info: "•",
};

function bar(score: number, width = 20): string {
  const filled = Math.round((score / 100) * width);
  return "█".repeat(filled) + "░".repeat(width - filled);
}

export function renderTerminal(r: Report, color = true): string {
  const C = color ? c : new Proxy({}, { get: () => "" }) as typeof c;
  const sc = color ? colorFor(r.score) : "";
  const L: string[] = [];
  L.push("");
  L.push(`${C.bold}  mcp-tokenlint${C.reset} ${C.dim}— MCP token-budget report${C.reset}`);
  L.push("");
  L.push(`  ${sc}${C.bold}Score ${r.score}/100  (grade ${r.grade})${C.reset}  ${sc}${bar(r.score)}${C.reset}`);
  L.push(`  ${C.dim}${r.totalTokens.toLocaleString()} tokens across ${r.toolCount} tools · avg ${r.avgTokensPerTool}/tool · counted with ${r.tokenizer}${C.reset}`);
  L.push("");
  L.push(`  ${C.bold}Sub-scores${C.reset}`);
  for (const [k, v] of Object.entries(r.subScores)) {
    const cc = color ? colorFor(v) : "";
    L.push(`    ${k.padEnd(14)} ${cc}${String(v).padStart(3)}${C.reset} ${cc}${bar(v, 14)}${C.reset}`);
  }
  L.push("");
  L.push(`  ${C.bold}Heaviest tools${C.reset}`);
  for (const t of r.tools.slice(0, 8)) {
    L.push(`    ${String(t.totalTokens).padStart(6)} tok  ${C.cyan}${t.name}${C.reset} ${C.dim}(desc ${t.descriptionTokens}, schema ${t.schemaTokens})${C.reset}`);
  }
  L.push("");
  if (r.findings.length) {
    L.push(`  ${C.bold}Suggestions${C.reset} ${C.dim}(est. recoverable: ~${r.estimatedSavings.toLocaleString()} tokens)${C.reset}`);
    for (const f of r.findings.slice(0, 12)) {
      const fc = f.severity === "error" ? C.red : f.severity === "warning" ? C.yellow : C.dim;
      const save = f.estimatedSavings > 0 ? `${C.dim} [~${f.estimatedSavings} tok]${C.reset}` : "";
      L.push(`    ${fc}${sevIcon[f.severity]}${C.reset} ${C.cyan}${f.tool}${C.reset} ${f.message}${save}`);
    }
    if (r.findings.length > 12) L.push(`    ${C.dim}…and ${r.findings.length - 12} more${C.reset}`);
  } else {
    L.push(`  ${C.green}No issues found — lean and clean.${C.reset}`);
  }
  L.push("");
  return L.join("\n");
}

export function renderMarkdown(r: Report): string {
  const emoji = r.score >= 90 ? "🟢" : r.score >= 50 ? "🟡" : "🔴";
  const L: string[] = [];
  L.push(`## ${emoji} MCP token-budget: **${r.score}/100** (grade ${r.grade})`);
  L.push("");
  L.push(`**${r.totalTokens.toLocaleString()} tokens** across **${r.toolCount} tools** (avg ${r.avgTokensPerTool}/tool). Estimated recoverable: **~${r.estimatedSavings.toLocaleString()} tokens**.`);
  L.push("");
  L.push("| Sub-score | Value |");
  L.push("|---|---|");
  for (const [k, v] of Object.entries(r.subScores)) L.push(`| ${k} | ${v}/100 |`);
  L.push("");
  if (r.tools.length) {
    L.push("<details><summary>Heaviest tools</summary>");
    L.push("");
    L.push("| Tokens | Tool | Description | Schema |");
    L.push("|---:|---|---:|---:|");
    for (const t of r.tools.slice(0, 10)) {
      L.push(`| ${t.totalTokens} | \`${t.name}\` | ${t.descriptionTokens} | ${t.schemaTokens} |`);
    }
    L.push("</details>");
    L.push("");
  }
  if (r.findings.length) {
    L.push("### Suggestions");
    for (const f of r.findings.slice(0, 25)) {
      const icon = f.severity === "error" ? "✖" : f.severity === "warning" ? "⚠️" : "ℹ️";
      const save = f.estimatedSavings > 0 ? ` _(~${f.estimatedSavings} tok)_` : "";
      L.push(`- ${icon} \`${f.tool}\` — ${f.message}${save}`);
    }
  } else {
    L.push("✅ No issues found — lean and clean.");
  }
  L.push("");
  L.push(`<sub>Counted deterministically with ${r.tokenizer} · generated by [mcp-tokenlint](https://github.com/fernforge/mcp-tokenlint)</sub>`);
  return L.join("\n");
}
